spring:
  datasource:
    url: jdbc:h2:~/findme;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
  flyway:
    enabled: true
    locations: classpath:db/migration/h2
  security: # Added for OAuth2
    oauth2:
      client:
        registration:
          google:
            client-id: your-google-client-id # Replace with your actual client ID
            client-secret: your-google-client-secret # Replace with your actual client secret
            redirect-uri: http://localhost:8080/login/oauth2/code/google

jwt: # Added for JWT
  secret: your-jwt-secret-key-base64-encoded-at-least-256-bit # Replace with a strong, base64 encoded secret
  expiration-minutes: 60 # Token expiration time in minutes

  bucket4j: # Added for Rate Limiting
    filters:
      - filter-url: "/**"
        rate-limit:
          bandwidths:
            - capacity: 60 # 60 requests per minute
              time: 1 # minute
              unit: minutes
        http-response-body-enabled: true
        http-response-body-json: true
        http-response-body-json-data: |
          {
            "code": "RATE_LIMITED",
            "message": "Too many requests. Please try again later.",
            "requestId": "${X-Request-Id}",
            "timestamp": "${T(java.time.LocalDateTime).now().format(T(java.time.format.DateTimeFormatter).ISO_INSTANT)}"
          }
        http-response-body-json-code: 429
        exclude-urls:
          - /api/health
          - /swagger-ui/**
          - /v3/api-docs/**

admin: # Added for Admin API
  token: your-admin-secret-token # Replace with a strong secret token for admin access
